# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('td', '0003_auto_20151217_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_pseudo', models.BooleanField(default=False)),
                ('contact_number', models.CharField(blank=True, max_length=200)),
                ('contact_person', models.EmailField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('province', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SlugField(unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Bible Translation Phase',
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField()),
                ('method', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('mast', 'MAST'), ('d43', 'door43'), ('ts', 'translationStudio'), ('memoq', 'MemoQ'), ('sovee', 'Sovee')], max_length=200)),
                ('completion_rate', models.PositiveSmallIntegerField(choices=[(2, '2%'), (25, '25%'), (50, '50%'), (75, '75%'), (99, '99%'), (100, '100%')])),
                ('completion_date', models.DateField()),
                ('qa_level', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')])),
                ('in_door43', models.BooleanField()),
                ('in_uw', models.BooleanField()),
                ('notes', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='td.Language')),
                ('partners', models.ManyToManyField(to='gl_tracking.Partner')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gl_tracking.Document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gl_tracking.Phase'),
        ),
    ]
