# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gl_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='code',
            field=models.SlugField(default='', max_length=4, unique=True),
        ),
    ]
