# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gl_tracking', '0002_document_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
