# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gl_tracking', '0003_auto_20151221_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gl_tracking.Phase')),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='document',
            name='type',
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gl_tracking.DocumentCategory'),
        ),
    ]
