# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gl_tracking', '0004_auto_20151221_2029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentcategory',
            options={'verbose_name': 'Document Category', 'verbose_name_plural': 'Document Categories'},
        ),
        migrations.AlterField(
            model_name='progress',
            name='completion_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='completion_rate',
            field=models.PositiveSmallIntegerField(choices=[(2, '2%'), (25, '25%'), (50, '50%'), (75, '75%'), (99, '99%'), (100, '100%')], null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='in_door43',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='in_uw',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='is_online',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='method',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline'), ('mast', 'MAST'), ('d43', 'door43'), ('ts', 'translationStudio'), ('memoq', 'MemoQ'), ('sovee', 'Sovee')], max_length=200),
        ),
        migrations.AlterField(
            model_name='progress',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='qa_level',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], null=True),
        ),
    ]
