# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gl_tracking', '0005_auto_20151221_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='completion_rate',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, '2%'), (25, '25%'), (50, '50%'), (75, '75%'), (99, '99%'), (100, '100%')], null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='partners',
            field=models.ManyToManyField(blank=True, to='gl_tracking.Partner'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='qa_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], null=True),
        ),
    ]
