# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gl_tracking', '0006_auto_20151222_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='identifier',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
    ]
