# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gl_tracking', '0007_progress_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='identifier',
            field=models.CharField(blank=True, default='', editable=False, max_length=200),
        ),
    ]
