# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gl_tracking', '0008_auto_20151222_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='identifier',
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together=set([]),
        ),
    ]
