# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 17:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('td', '0003_auto_20151217_0635'),
        ('gl_tracking', '0010_auto_20151222_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalDirector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='td.Region')),
                ('user_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='regionaldirector',
            unique_together=set([('first_name', 'middle_name', 'last_name')]),
        ),
    ]
