# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 17:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gl_tracking', '0011_auto_20151223_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionaldirector',
            name='user_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
