# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gl_tracking', '0012_auto_20151223_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionaldirector',
            name='region',
        ),
    ]
