# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gl_tracking', '0014_regionaldirector_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionaldirector',
            name='user_account',
        ),
    ]
