# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gl_tracking', '0015_remove_regionaldirector_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='is_done',
            field=models.BooleanField(default='false'),
        ),
    ]
