# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 19:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gl_tracking', '0017_auto_20160121_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='modifed_at',
            new_name='modified_at',
        ),
        migrations.AddField(
            model_name='progress',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='progress',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
