# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gl_tracking', '0019_auto_20160121_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='code',
            field=models.SlugField(default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Completion Date'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='completion_rate',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, '2%'), (25, '25%'), (50, '50%'), (75, '75%'), (99, '99%'), (100, '100%')], null=True, verbose_name='Completion Rate'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='in_door43',
            field=models.NullBooleanField(verbose_name='Available in Door43.org?'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='in_uw',
            field=models.NullBooleanField(verbose_name='Available in UnfoldingWord.org?'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='is_online',
            field=models.NullBooleanField(verbose_name='Is Online?'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='qa_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], null=True, verbose_name='QA Level'),
        ),
    ]
