# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0010_remove_region_wa_director'),
        ('gl_tracking', '0020_auto_20160125_1603'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='regionaldirector',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='regionaldirector',
            name='user',
        ),
        migrations.DeleteModel(
            name='RegionalDirector',
        ),
    ]
