# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gl_tracking', '0022_gldirector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gldirector',
            name='regions',
        ),
    ]
