# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0011_waregion'),
        ('gl_tracking', '0023_remove_gldirector_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='gldirector',
            name='regions',
            field=models.ManyToManyField(blank=True, to='td.WARegion'),
        ),
    ]
