# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gl_tracking', '0024_gldirector_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='gldirector',
            name='is_helper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gldirector',
            name='is_super',
            field=models.BooleanField(default=False),
        ),
    ]
