# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gl_tracking', '0025_gldirector_boolean_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='contact_number',
            new_name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='is_pseudo',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='state',
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='td.Country'),
        ),
    ]
