# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 06:35
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0002_language_anglicized_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='extra_data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='language',
            name='extra_data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
