# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gl_tracking', '0013_remove_regionaldirector_region'),
        ('td', '0003_auto_20151217_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='wa_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gl_tracking.RegionalDirector'),
        ),
    ]
