# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0004_region_wa_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='variance',
            field=models.ManyToManyField(blank=True, related_name='_language_variance_+', to='td.Language'),
        ),
    ]
