# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0005_language_variance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='variance',
        ),
        migrations.AddField(
            model_name='language',
            name='variants',
            field=models.ManyToManyField(blank=True, related_name='_language_variants_+', to='td.Language'),
        ),
    ]
