# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0006_auto_20160107_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='variants',
        ),
        migrations.AddField(
            model_name='language',
            name='is_variant_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='td.Language'),
        ),
    ]
