# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0007_auto_20160108_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='is_variant_of',
            new_name='variant_of',
        ),
    ]
