# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0008_auto_20160108_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='variant_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='td.Language'),
        ),
    ]
