# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0010_remove_region_wa_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageAltNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField()),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
        ),
    ]
