# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0010_remove_region_wa_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='WARegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'wa_region',
            },
        ),
    ]
