# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0011_langAltNames_as_property'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LanguageAltNames',
            new_name='LanguageAltName',
        ),
    ]
