# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0012_langAtlName_name_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagealtname',
            name='alternate_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='td.Language'),
        ),
    ]
