# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0012_language_wa_region'),
        ('td', '0013_langAltName_alternate_for_field'),
    ]

    operations = [
    ]
