# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0014_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languagealtname',
            name='alternate_for',
        ),
        migrations.AddField(
            model_name='language',
            name='alternate_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
