# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0016_language_alt_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='alternate_name',
        ),
    ]
