# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0018_add_language_alt_names'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='languagealtname',
            unique_together=set([('code', 'name')]),
        ),
    ]
