# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0019_languagealtname_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSONData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('name', models.SlugField()),
                ('data', jsonfield.fields.JSONField()),
            ],
        ),
    ]
