# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0020_jsondata_model_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='wa_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='td.WARegion'),
        ),
    ]
