# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0020_jsondata_model_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondata',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jsondata',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
