# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 19:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0003_questionnaire'),
        ('td', '0021_added_wa_region_to_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('direction', models.CharField(choices=[(b'l', b'ltr'), (b'r', b'rtl')], default=b'l', max_length=1)),
                ('app', models.CharField(blank=True, choices=[(b'td', b'translationDatabase'), (b'ts-android', b'translationStudio Android'), (b'ts-desktop', b'translationStudio Desktop'), (b'tr', b'translationRecorder')], max_length=5)),
                ('requester', models.CharField(max_length=100)),
                ('answers', jsonfield.fields.JSONField(blank=True)),
                ('request_id', models.SlugField(blank=True)),
                ('status', models.CharField(choices=[(b'p', b'Pending'), (b'a', b'Approved'), (b'r', b'Rejected')], default=b'p', max_length=1)),
                ('status_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='td.Country')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templanguage_created', to=settings.AUTH_USER_MODEL)),
                ('lang_assigned', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='td.Language')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templanguage_modified', to=settings.AUTH_USER_MODEL)),
                ('questionnaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='resources.Questionnaire')),
            ],
        ),
    ]
