# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 20:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('td', '0021_added_wa_region_to_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ietf_tag', models.CharField(max_length=12, unique=True)),
                ('common_name', models.CharField(max_length=100)),
                ('native_name', models.CharField(blank=True, max_length=100)),
                ('direction', models.CharField(choices=[(b'l', b'ltr'), (b'r', b'rtl')], default=b'l', max_length=1)),
                ('source_app', models.CharField(choices=[(b'td', b'translationDatabase'), (b'ts', b'translationStudio'), (b'ts-d', b'translationStudio Desktop'), (b'tr', b'translationRecorder')], max_length=5)),
                ('source_name', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[(b'p', b'Pending'), (b'a', b'Approved'), (b'r', b'Rejected')], default=b'p', max_length=1)),
                ('status_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templanguage_created', to=settings.AUTH_USER_MODEL)),
                ('lang_assigned', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='td.Language')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templanguage_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
