# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_create_questionnaire'),
        ('td', '0022_create_templanguage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templanguage',
            old_name='ietf_tag',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='templanguage',
            old_name='source_name',
            new_name='requester',
        ),
        migrations.RemoveField(
            model_name='templanguage',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='templanguage',
            name='common_name',
        ),
        migrations.RemoveField(
            model_name='templanguage',
            name='native_name',
        ),
        migrations.RemoveField(
            model_name='templanguage',
            name='source_app',
        ),
        migrations.AddField(
            model_name='templanguage',
            name='answers',
            field=jsonfield.fields.JSONField(blank=True),
        ),
        migrations.AddField(
            model_name='templanguage',
            name='app',
            field=models.CharField(blank=True, choices=[(b'td', b'translationDatabase'), (b'ts-android', b'translationStudio Android'), (b'ts-desktop', b'translationStudio Desktop'), (b'tr', b'translationRecorder')], max_length=5),
        ),
        migrations.AddField(
            model_name='templanguage',
            name='questionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='resources.Questionnaire'),
        ),
        migrations.AddField(
            model_name='templanguage',
            name='request_id',
            field=models.SlugField(blank=True),
        ),
    ]
