# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-08 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0022_templanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templanguage',
            name='app',
            field=models.CharField(blank=True, choices=[(b'td', b'translationDatabase'), (b'ts-android', b'translationStudio Android'), (b'ts-desktop', b'translationStudio Desktop'), (b'tr', b'translationRecorder')], max_length=10),
        ),
    ]
