# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-01 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0024_auto_20160329_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={},
        ),
        migrations.AddField(
            model_name='templanguage',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='td.Country'),
        ),
    ]
