# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-01 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0025_templanguage_add_name_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='templanguage',
            name='name',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
