# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 18:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publishing', '0009_publishrequest_license_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishrequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name=b'Rejected at'),
        ),
        migrations.AddField(
            model_name='publishrequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Rejected by'),
        ),
    ]
