# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0010_publishrequest_reject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcedocument',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='td.Language'),
        ),
    ]
