# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 06:35
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='extra_data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='resource',
            name='extra_data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='title',
            name='extra_data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
