# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0021_added_wa_region_to_country'),
        ('resources', '0002_auto_20151217_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', jsonfield.fields.JSONField()),
                ('field_mapping', jsonfield.fields.JSONField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='td.Language')),
            ],
        ),
    ]
