# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-01 15:19
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_create_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='field_mapping',
            field=jsonfield.fields.JSONField(blank=True),
        ),
    ]
