from django.conf.urls import patterns, url

from .views import (
    HomeView,
    RegionListView,
    RegionDetailView,
    CountryListView,
    CountryDetailView,
    CountryEditView,
    LanguageCreateView,
    LanguageDetailView,
    LanguageEditView,
    LanguageListView,
    AjaxLanguageListView,
    AjaxLanguageGatewayListView,
    NetworkCreateView,
    NetworkDetailView,
    NetworkEditView,
    NetworkListView,
    ResourceCreateView,
    ResourceEditView,
    PublisherListView,
    PublisherDetailView,
    PublisherEditView,
    PublisherCreateView,
    TitleListView,
    TitleDetailView,
    TitleEditView,
    TitleCreateView,
    country_tree_data,
    upload_gateway_flag_file,
    upload_rtl_list,
    country_map_data,
)


urlpatterns = patterns(
    "",
    url(r"^$", HomeView.as_view(), name="uw_home"),
    url(r"networks/$", NetworkListView.as_view(), name="network_list"),
    url(r"networks/create/$", NetworkCreateView.as_view(), name="network_create"),
    url(r"networks/(?P<pk>\d+)/$", NetworkDetailView.as_view(), name="network_detail"),
    url(r"networks/(?P<pk>\d+)/edit/$", NetworkEditView.as_view(), name="network_edit"),

    url(r"regions/$", RegionListView.as_view(), name="region_list"),
    url(r"regions/(?P<slug>\w+)/$", RegionDetailView.as_view(), name="region_detail"),
    url(r"countries/$", CountryListView.as_view(), name="country_list"),
    url(r"countries/(?P<pk>\d+)/$", CountryDetailView.as_view(), name="country_detail"),
    url(r"countries/(?P<pk>\d+)/edit/$", CountryEditView.as_view(), name="country_edit"),
    url(r"countries/(?P<pk>\d+)/languages/create/$", LanguageCreateView.as_view(), name="language_create"),
    url(r"ajax/languages/$", AjaxLanguageListView.as_view(), name="ajax_ds_uw_languages"),
    url(r"ajax/languages_gateway/(?P<pk>\d+)/$", AjaxLanguageGatewayListView.as_view(), name="ajax_ds_uw_languages_gateway"),
    url(r"languages/$", LanguageListView.as_view(), name="language_list"),
    url(r"languages/(?P<pk>\d+)/$", LanguageDetailView.as_view(), name="language_detail"),
    url(r"languages/(?P<pk>\d+)/edit/$", LanguageEditView.as_view(), name="language_edit"),
    url(r"languages/(?P<pk>\d+)/resources/create/$", ResourceCreateView.as_view(), name="resource_create"),
    url(r"languages/(?P<pk>\d+)/resources/edit/$", ResourceEditView.as_view(), name="resource_edit"),
    url(r"publishers/$", PublisherListView.as_view(), name="publisher_list"),
    url(r"publishers/create/$", PublisherCreateView.as_view(), name="publisher_create"),
    url(r"publishers/(?P<pk>\d+)/$", PublisherDetailView.as_view(), name="publisher_detail"),
    url(r"publishers/(?P<pk>\d+)/edit/$", PublisherEditView.as_view(), name="publisher_edit"),
    url(r"titles/$", TitleListView.as_view(), name="title_list"),
    url(r"titles/create/$", TitleCreateView.as_view(), name="title_create"),
    url(r"titles/(?P<slug>[-\w\d]+)/$", TitleDetailView.as_view(), name="title_detail"),
    url(r"titles/(?P<slug>[-\w\d]+)/edit/$", TitleEditView.as_view(), name="title_edit"),

    url(r"gateway_language_flag/update/$", upload_gateway_flag_file, name="gateway_flag_update"),
    url(r"rtl_languages/update/$", upload_rtl_list, name="rtl_languages_update"),

    url(r"country_gateways.json$", country_tree_data, name="country_tree_data"),
    url(r"country_map_data.json$", country_map_data, name="country_map_data"),
)
