# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gl_tracking', '0026_update_partner'),
        ('tracking', '0026_auto_20151216_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='charter',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gl_tracking.Partner'),
        ),
        migrations.AddField(
            model_name='event',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gl_tracking.Partner'),
        ),
    ]
