# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-21 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0027_added_partner_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='charter',
            name='new_start',
            field=models.BooleanField(default=False),
        ),
    ]
